name: Dismiss PR approvals on non-maintainer pushes

on:
  pull_request:
    types:
      - synchronize

jobs:
  dismiss-approvals:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-latest
    steps:
      - id: list-maintainers
        name: Get maintainer list
        run: |
          # Below are the public members of Homebrew, obtained with:
          #   gh api '/orgs/Homebrew/public_members?per_page=100' --jq '[.[].login] | sort_by(ascii_upcase)'
          # TODO: Use `gh api` to get the actual list of Homebrew/core
          # maintainers (@Homebrew/core team members) instead. To do that, we
          # need a token with the "admin:org" scope.
          homebrew_public_members='["alebcay","bayandin","bevanjkay","Bo98","branchvincent","BrewTestBot","carlocab","chenrui333","cho-m","colindean","danielnachun","dawidd6","DomT4","dtrodrigues","EricFromCanada","fxcoudert","gdams","gromgit","iMichka","issyl0","jacobbednarz","jonchang","lembacon","maxim-belkin","miccal","MikeMcQuaid","mistydemeo","Moisan","nandahkrishna","p-linnane","ran-dall","razvanazamfirei","reitermarkus","Rylan12","samford","scpeters","sjackman","SMillerDev","tani","victorpopkov","vitorgalvao","whoiswillma","woodruffw","xu-cheng","zachauten","zbeekman","ZhongRuoyu","zmwangx"]'
          echo "maintainers=$homebrew_public_members" >> "$GITHUB_OUTPUT"
      - name: Dismiss approvals
        if: >
          failure() ||
          (!contains(fromJson(steps.list-maintainers.outputs.maintainers), github.triggering_actor) &&
           github.triggering_actor != 'BrewTestBot')
        uses: Homebrew/actions/dismiss-approvals@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
          pr: ${{github.event.pull_request.number}}
          message: ":warning: PR branch was modified by a non-maintainer."
