name: Remove `CI-long-timeout` labels

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'Homebrew' &&
      github.event.workflow_run.event == 'pull_request'
    permissions:
      actions: read # for `gh run download`
      pull-requests: write # for `gh pr edit`
    steps:
      - name: Download `pull-number` artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_ID: ${{ github.event.workflow_run.id }}
        run: gh run download --name pull-number "$WORKFLOW_ID"

      - run: echo "number=$(cat number)" >> "$GITHUB_OUTPUT"
        id: pr

      - name: Remove `CI-long-timeout` label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ steps.pr.outputs.number }}
        run: |
          echo "::notice ::Removing \`CI-long-timeout\` label from PR #$PR"
          gh pr edit "$PR" --remove-label CI-long-timeout
