name: Remove `CI-long-timeout` labels

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'Homebrew' &&
      github.event.workflow_run.event == 'pull_request'
    permissions:
      pull-requests: write # for `gh pr edit`
    steps:
      - name: Dump event JSON
        run: |
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          jq . "$GITHUB_EVENT_PATH" | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

          echo '```' >> "$GITHUB_STEP_SUMMARY"
          jq .workflow_run "$GITHUB_EVENT_PATH" | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

          echo '```' >> "$GITHUB_STEP_SUMMARY"
          jq .workflow_run.pull_requests "$GITHUB_EVENT_PATH" | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Remove `CI-long-timeout` label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULLS: ${{ toJson(github.event.workflow_run.pull_requests.*.number) }}
        run: |
          while read -r PR
          do
            gh pr edit "$PR" --remove-label CI-long-timeout
          done < <(jq --raw-output '.[]' <<< "$PULLS")
