name: Scheduled online check
on:
  push:
    paths:
      - .github/workflows/scheduled.yml
  schedule:
    # Once every day at 1AM
    - cron: "0 1 * * *"

concurrency:
  group: scheduled
  cancel-in-progress: true

jobs:
  create_matrix:
    # if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ubuntu-22.04
    outputs:
      json: ${{ steps.matrix.outputs.json }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - id: matrix
        run: |
          formula=$(find  $(brew --repo homebrew/core)/Formula |  shuf -n10 | xargs -I{} basename {} .rb)
          json=$(brew info --json=v2 $formula | jq [.formulae[].name])
          echo "json=${json}" >> $GITHUB_OUTPUT
          echo "json=${json}"
  audit_online:
    # if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ubuntu-22.04
    needs: create_matrix
    strategy:
      matrix:
        formula: ${{ needs.create_matrix.outputs.json }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Check formula for missing upstreams etc.
        run: brew audit --online --skip-style --only github_repository_archived,gitlab_repository_archived,homepage ${{ matrix.formula }}
        
      - name: Check formula for missing sources.
        run: brew fetch -s ${{ matrix.formula }}
